# Generated by Django 2.2.24 on 2021-07-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0095_auto_20210518_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOverrideError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACTIVE'), (403, 'INVALID_CREDENTIALS'), (432, 'INVALID_MFA'), (530, 'END_SITE_DOWN'), (531, 'IP_BLOCKED'), (532, 'TRIPPED_CAPTCHA'), (5, 'INCOMPLETE'), (434, 'LOCKED_BY_ENDSITE'), (429, 'RETRY_LIMIT_REACHED'), (503, 'RESOURCE_LIMIT_REACHED'), (520, 'UNKNOWN_ERROR'), (9, 'MIDAS_UNREACHABLE'), (404, 'AGENT_NOT_FOUND'), (10, 'WALLET_ONLY'), (533, 'PASSWORD_EXPIRED'), (900, 'JOIN'), (444, 'NO_SUCH_RECORD'), (536, 'CONFIGURATION_ERROR'), (535, 'NOT_SENT'), (445, 'ACCOUNT_ALREADY_EXISTS'), (537, 'SERVICE_CONNECTION_ERROR'), (401, 'VALIDATION_ERROR'), (406, 'PRE_REGISTERED_CARD'), (446, 'FAILED_UPDATE'), (447, 'SCHEME_REQUESTED_DELETE'), (204, 'PENDING_MANUAL_CHECK'), (436, 'CARD_NUMBER_ERROR'), (437, 'LINK_LIMIT_EXCEEDED'), (438, 'CARD_NOT_REGISTERED'), (439, 'GENERAL_ERROR'), (441, 'JOIN_IN_PROGRESS'), (538, 'JOIN_ERROR'), (442, 'JOIN_ASYNC_IN_PROGRESS'), (901, 'ENROL_FAILED'), (902, 'REGISTRATION_FAILED')])),
                ('reason_code', models.CharField(choices=[('X000', 'X000'), ('X100', 'X100'), ('X101', 'X101'), ('X102', 'X102'), ('X103', 'X103'), ('X104', 'X104'), ('X105', 'X105'), ('X200', 'X200'), ('X201', 'X201'), ('X202', 'X202'), ('X203', 'X203'), ('X300', 'X300'), ('X301', 'X301'), ('X302', 'X302'), ('X303', 'X303'), ('X304', 'X304')], max_length=50)),
                ('error_slug', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.Scheme')),
            ],
            options={
                'unique_together': {('error_code', 'reason_code', 'scheme')},
            },
        ),
    ]
